
CXX		= $(MYSW_CXX)
LD              = g++
LDFLAGS         += -Wl,-rpath,$(MYSW_DIR)/lib
FFLAGS          += -Wall
FLDFLAGS        += -lstdc++ -shared 
CXXFLAGS        += -g -O3 -std=c++11 $(MYSW_CXXSTDFLAG) -W -Wall -Wno-deprecated -fPIC -D_CORE_$(shell uname -s)_
SOMAKER         = g++
SOFLAGS         = -g -fPIC -shared
